---
jenkins_dest: /opt/jenkins
jenkins_home: /var/lib/jenkins
jenkins:
  cli: "{{ jenkins_dest }}/jenkins-cli.jar"
  updates: "{{ jenkins_dest }}/updates_jenkins.json"
  port: 8081
  plugins:
    - 'checkstyle'
    - 'cloverphp'
    - 'crap4j'
    - 'dry'
    - 'htmlpublisher'
    - 'jdepend'
    - 'plot'
    - 'pmd'
    - 'violations'
    - 'warnings'
    - 'xunit'
    - 'git'
    - 'greenballs'